"""empty message

Revision ID: e3799d49c951
Revises: 
Create Date: 2018-12-27 10:17:30.028737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3799d49c951'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('esbi_monitor_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('slid', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esbi_monitor_users_email'), 'esbi_monitor_users', ['email'], unique=True)
    op.create_index(op.f('ix_esbi_monitor_users_first_name'), 'esbi_monitor_users', ['first_name'], unique=False)
    op.create_index(op.f('ix_esbi_monitor_users_last_name'), 'esbi_monitor_users', ['last_name'], unique=False)
    op.create_index(op.f('ix_esbi_monitor_users_slid'), 'esbi_monitor_users', ['slid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esbi_monitor_users_slid'), table_name='esbi_monitor_users')
    op.drop_index(op.f('ix_esbi_monitor_users_last_name'), table_name='esbi_monitor_users')
    op.drop_index(op.f('ix_esbi_monitor_users_first_name'), table_name='esbi_monitor_users')
    op.drop_index(op.f('ix_esbi_monitor_users_email'), table_name='esbi_monitor_users')
    op.drop_table('esbi_monitor_users')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
